# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='stu_id',
            new_name='stu_num_id',
        ),
    ]
