# Generated by Django 2.2.3 on 2019-08-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20190527_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='merOrderId',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
