# Generated by Django 2.1.5 on 2019-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_newsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_news_mapping_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('news_id_list', models.CharField(max_length=2000)),
            ],
        ),
    ]
