# Generated by Django 2.1.5 on 2019-02-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_usernewsmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernewsmapping',
            old_name='news_id_list',
            new_name='news_id',
        ),
    ]
