# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20)),
                ('s_type', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('disk', models.CharField(max_length=20)),
                ('ipmi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('dev_source', models.CharField(max_length=20)),
                ('dev_model', models.CharField(max_length=20)),
                ('dev_role', models.CharField(max_length=20)),
                ('dev_user', models.CharField(max_length=20)),
                ('approver', models.CharField(max_length=20)),
                ('dev_desc', models.CharField(max_length=20)),
                ('dev_status', models.CharField(max_length=20)),
                ('borrow_time_limit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
