# Generated by Django 2.1.5 on 2019-02-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20190207_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(default=1305678213, max_length=200),
            preserve_default=False,
        ),
    ]
