# Generated by Django 2.1.5 on 2019-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_userinfo_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=200)),
                ('news_title', models.CharField(max_length=200)),
                ('news_date', models.CharField(max_length=200)),
                ('news_author', models.CharField(max_length=200)),
                ('news_details', models.CharField(max_length=5000)),
            ],
        ),
    ]
