# Generated by Django 2.1.5 on 2019-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20190207_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=200)),
                ('game_name', models.CharField(max_length=200)),
                ('game_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
